### ISSUE TITLE
Fails with latest node version

### ISSUE THREAD

**Issue by IObert** [SAP/cloud-mta-build-tool#368]
Running the make process fails with the latest node version. The setup worked with an older node version

Please provide the following info:

  - MBT Version:  0.2.5
  - OS Version: macOS 10.14.5
  - If possible, provide a link to the project. Can use any project or this one https://github.com/IObert/Beershop

Steps to Reproduce:

1. create project
2. mbt init
3.  make -f Makefile.mta p=cf
```
[2019-05-17 18:08:35]  INFO validating the MTA project
[2019-05-17 18:08:35]  INFO validating the MTA project
[2019-05-17 18:08:35]  INFO building the "beershop-db" module...
[2019-05-17 18:08:35]  INFO executing the [npm install] command...
..
> @sap/hana-client@2.3.123 install /Users/d056949/Desktop/beershop/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node build.js

..Error: Command failed: node-gyp build
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:298:11: error: no template named 'Handle'
                        Handle<Value>                           arg,
                        ^
../src/h/hana_utils.h:301:6: error: redefinition of 'getBindParameters' as different kind of symbol
bool getBindParameters( Handle<Value>                           arg,
     ^
../src/h/hana_utils.h:294:6: note: previous definition is here
bool getBindParameters( std::vector<char*>                      &string_params,
     ^
../src/h/hana_utils.h:301:25: error: use of undeclared identifier 'Handle'
bool getBindParameters( Handle<Value>                           arg,
                        ^
../src/h/hana_utils.h:301:32: error: 'Value' does not refer to a value
bool getBindParameters( Handle<Value>                           arg,
                               ^
/Users/d056949/.node-gyp/12.2.0/include/node/v8.h:2240:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:301:43: error: use of undeclared identifier 'arg'
bool getBindParameters( Handle<Value>                           arg,
                                                                ^
../src/h/hana_utils.h:302:65: error: expected '(' for function-style cast or type construction
                        int                                     row_param_count,
                        ~~~                                     ^
../src/h/hana_utils.h:303:65: error: expected '(' for function-style cast or type construction
                        std::vector<dbcapi_bind_data*>          &params,
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ^
../src/h/hana_utils.h:303:66: error: use of undeclared identifier 'params'
                        std::vector<dbcapi_bind_data*>          &params,
                                                                 ^
../src/h/hana_utils.h:304:45: error: expected '(' for function-style cast or type construction
                        std::vector<size_t> &                   buffer_size );
                        ~~~~~~~~~~~~~~~~~~~ ^
../src/h/hana_utils.h:304:63: error: use of undeclared identifier 'buffer_size'
                        std::vector<size_t> &                   buffer_size );
                                                                ^
../src/h/hana_utils.h:310:26: error: use of undeclared identifier 'Handle'
bool getInputParameters( Handle<Value>                      arg,
                         ^
../src/h/hana_utils.h:310:33: error: 'Value' does not refer to a value
bool getInputParameters( Handle<Value>                      arg,
                                ^
/Users/d056949/.node-gyp/12.2.0/include/node/v8.h:2240:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:310:61: error: use of undeclared identifier 'arg'
bool getInputParameters( Handle<Value>                      arg,
                                                            ^
../src/h/hana_utils.h:311:57: error: expected '(' for function-style cast or type construction
                         std::vector<dbcapi_bind_data*> &   params,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../src/h/hana_utils.h:311:61: error: use of undeclared identifier 'params'
                         std::vector<dbcapi_bind_data*> &   params,
                                                            ^
../src/h/hana_utils.h:312:26: error: unexpected type name 'dbcapi_stmt': expected expression
                         dbcapi_stmt *                      stmt,
                         ^
../src/h/hana_utils.h:312:61: error: use of undeclared identifier 'stmt'; did you mean 'stat'?
                         dbcapi_stmt *                      stmt,
                                                            ^~~~
                                                            stat
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stat.h:361:9: note: 'stat' declared here
int     stat(const char *, struct stat *) __DARWIN_INODE64(stat);
        ^
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:313:30: error: expected '(' for function-style cast or type construction
                         int &                              errCode,
                         ~~~ ^
../src/h/hana_utils.h:313:61: error: use of undeclared identifier 'errCode'; did you mean 'strmode'?
                         int &                              errCode,
                                                            ^~~~~~~
                                                            strmode
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/string.h:164:7: note: 'strmode' declared here
void     strmode(int __mode, char *__bp);
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [Release/obj.target/hana-client/src/hana.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/d056949/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/d056949/.nvm/versions/node/v12.2.0/bin/node" "/Users/d056949/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/d056949/Desktop/beershop/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Socket.<anonymous> (internal/child_process.js:416:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp build'
}   CXX(target) Release/obj.target/hana-client/src/hana.o

npm WARN deploy@ No description
npm WARN deploy@ No repository field.
npm WARN deploy@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @sap/hana-client@2.3.123 install: `node build.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @sap/hana-client@2.3.123 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/d056949/.npm/_logs/2019-05-17T16_08_39_826Z-debug.log
[2019-05-17 18:08:39] ERROR build of the "beershop-db" module failed when executing commands: execution of the "/Users/d056949/.nvm/versions/node/v12.2.0/bin/npm" command failed while waiting for finish: exit status 255
make: *** [beershop-db] Error 1
```

**Comment by ShimiT** [comment]
HI,

From the error, it seems that the problem is due to API incompatibility (Hana-client) which probably changed during major released version ( node v12.x.x), you can try it using the following:

1. `cd db` 
2. run `npm install`  

You should get the same error as the `mbt` is utilizing the installed node on your mac.
If you have any doubts, please let me know.


Regards,
Shimon

**Comment by IObert** [comment]
You're right. The issue is not related to this project.
Thanks for pointing me in the right direction!

**Comment by gregorwolf** [comment]
Thanks a lot for this incident. It helped me to get a successful installation of

```
npm i -g @sap/hdi-deploy
```

after downgrading from node/12.2.0 to node/10.16.0.
