### ISSUE TITLE
While running MBT build to build mtar file getting error

### ISSUE THREAD

**Issue by AbhijeetKankani** [SAP/cloud-mta-build-tool#866]
Do you want to request a feature or report a bug?
yes
- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- I already checked
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 
  Using  Cloud MTA Build Tool version 1.1.1

Please provide the following info:

  - MBT Version:  Cloud MTA Build Tool version 1.1.1
  - OS Version:  it is in BAS
  - If possible, provide a link to the project. not possible

Steps to Reproduce:

1. Run command mbt build (one UI5 app along with the DMS app) getting below error --

[2021-05-15 15:15:56]  INFO Cloud MTA Build Tool version 1.1.1
[2021-05-15 15:15:56]  INFO generating the "Makefile_20210515151556.mta" file...
[2021-05-15 15:15:56]  INFO done
[2021-05-15 15:15:56]  INFO executing the "make -f Makefile_20210515151556.mta p=cf mtar= strict=true mode=" command...
[2021-05-15 15:15:56]  INFO validating the MTA project
[2021-05-15 15:15:56]  INFO running the "before-all" build...
[2021-05-15 15:15:56]  INFO executing the "npm install" command...
.........npm WARN scp-nodejs-dms@0.0.1 No description
npm WARN scp-nodejs-dms@0.0.1 No repository field.
npm WARN scp-nodejs-dms@0.0.1 No license field.

----
.npx: installed 12 in 1.407s
.INFO: Using local @ui5/cli installation

info builder:builder Building project dmsui not including dependencies...
info builder:builder 🛠  (1/1) Building project dmsui
info builder:builder application dmsui 🔨 (1/13) Running task escapeNonAsciiCharacters...
info builder:builder application dmsui 🔨 (2/13) Running task replaceCopyright...
info builder:builder application dmsui 🔨 (3/13) Running task replaceVersion...
info builder:builder application dmsui 🔨 (4/13) Running task generateFlexChangesBundle...
info builder:builder application dmsui 🔨 (5/13) Running task generateManifestBundle...
info builder:builder application dmsui 🔨 (6/13) Running task generateComponentPreload...
ERR! lbt:resources:ResourcePool Error: Line 17: Unexpected token (
ERR! lbt:resources:ResourcePool     at ErrorHandler.constructError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5012:22)
ERR! lbt:resources:ResourcePool     at ErrorHandler.createError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5028:27)
ERR! lbt:resources:ResourcePool     at Parser.unexpectedTokenError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1985:39)
ERR! lbt:resources:ResourcePool     at Parser.throwUnexpectedToken (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1995:21)
ERR! lbt:resources:ResourcePool     at Parser.parseVariableIdentifier (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3594:27)
ERR! lbt:resources:ResourcePool     at Parser.parseFunctionDeclaration (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4316:24)
ERR! lbt:resources:ResourcePool     at Parser.parseLabelledStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4013:41)
ERR! lbt:resources:ResourcePool     at Parser.parseStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4122:97)
ERR! lbt:resources:ResourcePool     at Parser.parseStatementListItem (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3393:31)
ERR! lbt:resources:ResourcePool     at Parser.parseFunctionSourceElements (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4195:29)
ERR! lbt:resources:ResourcePool  failed to parse or analyze %s: ns/dmsui/controller/View1.controller.js { Error: Line 17: Unexpected token (
ERR! lbt:resources:ResourcePool     at ErrorHandler.constructError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5012:22)
ERR! lbt:resources:ResourcePool     at ErrorHandler.createError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5028:27)
ERR! lbt:resources:ResourcePool     at Parser.unexpectedTokenError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1985:39)
ERR! lbt:resources:ResourcePool     at Parser.throwUnexpectedToken (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1995:21)
ERR! lbt:resources:ResourcePool     at Parser.parseVariableIdentifier (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3594:27)
ERR! lbt:resources:ResourcePool     at Parser.parseFunctionDeclaration (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4316:24)
ERR! lbt:resources:ResourcePool     at Parser.parseLabelledStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4013:41)
ERR! lbt:resources:ResourcePool     at Parser.parseStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4122:97)
ERR! lbt:resources:ResourcePool     at Parser.parseStatementListItem (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3393:31)
ERR! lbt:resources:ResourcePool     at Parser.parseFunctionSourceElements (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4195:29)
ERR! lbt:resources:ResourcePool   index: 543,
ERR! lbt:resources:ResourcePool   lineNumber: 17,
ERR! lbt:resources:ResourcePool   description: 'Unexpected token (',
ERR! lbt:resources:ResourcePool   stack:
ERR! lbt:resources:ResourcePool    'Error: Line 17: Unexpected token (\n    at ErrorHandler.constructError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5012:22)\n    at ErrorHandler.createError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:5028:27)\n    at Parser.unexpectedTokenError (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1985:39)\n    at Parser.throwUnexpectedToken (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:1995:21)\n    at Parser.parseVariableIdentifier (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3594:27)\n    at Parser.parseFunctionDeclaration (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4316:24)\n    at Parser.parseLabelledStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4013:41)\n    at Parser.parseStatement (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4122:97)\n    at Parser.parseStatementListItem (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:3393:31)\n    at Parser.parseFunctionSourceElements (/home/user/projects/scp-nodejs-dms/node_modules/esprima/dist/esprima.js:4195:29)' }
ERR! builder:builder Build failed in 383 ms
info builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
Unexpected token: punc (()

For details, execute the same command again with an additional '--verbose' parameter
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dmsui@0.0.1 build: `npm run clean && ui5 build --include-task=generateManifestBundle generateCachebusterInfo && npm run zip`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dmsui@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-15T15_16_12_876Z-debug.log
[2021-05-15 15:16:12] ERROR could not build the "dmsui" module: could not execute the "npm run build" command: exit status 1
make: *** [Makefile_20210515151556.mta:37: dmsui] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20210515151556.mta p=cf mtar= strict=true mode=" command: exit status 2

**Comment by AbhijeetKankani** [comment]
Issue is relating to UI5 Tooling
