### ISSUE TITLE
npm install failing on Windows 64 bit

### ISSUE THREAD

**Issue by MFredX** [SAP/cloud-mta-build-tool#918]
**Description**

I am having trouble installing mbt using npm on my Windows device. Would greatly appreciate some pointers if this issue can be resolved from my end.

  - **MBT Version**: 1.2.7
  - **OS Version**: Windows 10 64 bit

Steps to Reproduce:

1. npm install -g mbt

**Output**

```
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
C:\Users\self\AppData\Roaming\npm\mbt -> C:\Users\self\AppData\Roaming\npm\node_modules\mbt\bin\mbt

> mbt@1.2.7 install C:\Users\self\AppData\Roaming\npm\node_modules\mbt
> binwrap-install

C:\Users\self\AppData\Roaming\npm\node_modules\mbt\node_modules\binwrap\install.js:18
    throw new Error("No binaries are available for your platform: " + buildId);
    ^

Error: No binaries are available for your platform: win32-ia32
    at install (C:\Users\self\AppData\Roaming\npm\node_modules\mbt\node_modules\binwrap\install.js:18:11)
    at Object.install (C:\Users\self\AppData\Roaming\npm\node_modules\mbt\node_modules\binwrap\index.js:14:14)
    at Object.<anonymous> (C:\Users\self\AppData\Roaming\npm\node_modules\mbt\node_modules\binwrap\bin\binwrap-install:18:9)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mbt@1.2.7 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mbt@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\self\AppData\Roaming\npm-cache\_logs\2021-11-30T23_46_56_243Z-debug.log
```

**Comment by adssidhu86** [comment]
I think this issue is due to binwrap. Binwrap is still showing request as dependency on github and npm (request is depreceated)  [https://github.com/avh4/binwrap/issues/25](url)

![binwrap_npm_dependency](https://user-images.githubusercontent.com/32054618/144188927-e4593535-a22a-44bb-95fe-2e533fbc213f.jpg)

**Comment by MFredX** [comment]
@adssidhu86 Thanks for you response.
Is there any workaround of any sort?

**Comment by adssidhu86** [comment]
@MFredX Only workaround I can think of is to force install this package by making npm ignore warning. This obviously means we will continue to use deprecated request package ( along with request-promise).

Below steps worked for me 

`npm cache clean --force `
`npm install --silent -g mbt`
![MBT_Workaround](https://user-images.githubusercontent.com/32054618/145854647-3f95a112-0d9b-46a8-9d7a-6ab015b47576.jpg)

**Comment by MFredX** [comment]
@adssidhu86 Thanks! This did solve my problem for the time being.
